logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/area_cn?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4
      idle-timeout: 120000
      max-lifetime: 240000
      validation-timeout: 3000
      connection-init-sql: 'SELECT 1'

crawl:
  root-url: 'https://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2023/'
  regex:
    - '<td><a href="(\d{2}).html">([\u4e00-\u9fa5]+)<br /></a></td>'
    - '<tr class="citytr"><td>(<a href="\d{2}/\d{4}.html">)?(\d{6})000000(</a>)?</td><td>(<a href="\d{2}/\d{4}.html">)?([\u4e00-\u9fa5]+)(</a>)?</td></tr>'
    - '<tr class="countytr"><td>(<a href="\d{2}/\d{6}.html">)?(\d{6})000000(</a>)?</td><td>(<a href="\d{2}/\d{6}.html">)?([\u4e00-\u9fa5]+)(</a>)?</td></tr>'
